baseURL = "https://serene-morse-0e258c.netlify.app/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-m10c-master"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[params]
author: Name of the author
description: Short description of the author
avatar: Path of file containing the author avatar image

[[menu.main]]
name = "Introduction"
weight = 1
url = "/introduction/"

name = "Test Annotated Definitions"
weight = 2
url = "/TestAnnotatedDef/"

name = "Test Resource Guide"
weight = 3
url = "/TestResourceGuide/"

name = "Test Walkthrough"
weight = 4
url = "/TestWalkthrough/"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"
